[package]
name = "ctranslate2"
version = "0.1.0"
authors = ["Junpei Kawamoto <kawamoto.junpei@gmail.com>"]
edition = "2021"
description = "Rust bindings for OpenNMT/CTranslate2"
repository = "https://github.com/jkawamoto/ctranslate2-rs"
license-file = "LICENSE"


[dependencies]
ctranslate2-sys = { path = "sys" }
anyhow = "1.0.71"
tokenizers = "0.13.3"


[build-dependencies]
