[package]
name = "ct2rs"
version = "0.4.6"
authors = ["Junpei Kawamoto <kawamoto.junpei@gmail.com>"]
edition = "2021"
description = "Rust bindings for OpenNMT/CTranslate2"
repository = "https://github.com/jkawamoto/ctranslate2-rs"
license = "MIT"
keywords = ["ctranslate2", "bindings", "llm"]
categories = ["api-bindings"]
include = [
    "/include",
    "/src",
    "/build.rs",
    "/LICENSE",
    "/CTranslate2/CMakeLists.txt",
    "/CTranslate2/LICENSE",
    "/CTranslate2/cmake",
    "/CTranslate2/cpp",
    "/CTranslate2/include",
    "/CTranslate2/python",
    "/CTranslate2/src",
    "/CTranslate2/third_party",
    "!/CTranslate2/**/.*",
    "!/CTranslate2/**/test",
    "!/CTranslate2/**/docs",
    "!/CTranslate2/**/media",
]

[dependencies]
cxx = { version = "1.0.121", features = ["c++17"] }
anyhow = "1.0.81"
tokenizers = "0.15.2"
intel-mkl-src = { version = "0.8.1", optional = true }


[build-dependencies]
cmake = "0.1.50"
cxx-build = "1.0.121"


[workspace]
members = ["examples/nllb", "examples/generator"]


[features]
default = []
mkl = ["dep:intel-mkl-src"]
