[package]
name = "ctranslate2-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.79"
cmake = "0.1.50"
bindgen = "0.65.1"
