[package]
name = "ctranslate2-sample"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctranslate2 = { path = ".." }
anyhow = "1.0.71"

[build-dependencies]
